# test.type = 'error'
#
# [test.metadata]
# error = 'EvalError::BlameError'
let 'Foo x = {bar = 1}  in
x
